version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger
      POSTGRES_DB: ledger
    ports:
      - '5437:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql