spring:
  application:
    name: ledger
  config:
    import: "optional:configserver:http://localhost:9000"
  cloud:
    config:
      fail-fast: true
      enabled: false


#spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/ledger
    username: ledger
    password: ledger
  flyway:
    enabled: false
    locations: classpath:db/migration

  r2dbc:
    url: r2dbc:postgresql://localhost:5437/ledger
    username: ledger
    password: ledger
  kafka:
    bootstrap-servers: localhost:9094,localhost:19094,localhost:29094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ledger-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  data:
    redis:
      cluster:
        nodes: localhost:6379,localhost:6380,localhost:6381,localhost:6382,localhost:6383,localhost:6384,localhost:6385,localhost:6386,localhost:6387,localhost:6388
        max-redirects: 3
        password: bitnami
        timeout: 500ms
        connect-ip: localhost
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  elasticsearch:
    rest:
      uris: http://localhost:9200

logging:
  level:
    org.springframework.batch: DEBUG
    org.springframework.jdbc: DEBUG
server:
  port: 8086
wallet:
  uri: "http://localhost:8083"
nft:
  uri: "http://localhost:8082/v1/nft"
